### ISSUE TITLE
扫描时出现错误

### ISSUE THREAD

**Issue by tseflcz** [zyr17/AmenomaCocogoat#3]
Amenoma扫描时出现错误，log文件报错如下：
Traceback (most recent call last):
  File "UIMain.py", line 640, in scanArts
  File "art_scanner_logic.py", line 152, in scanRows
  File "UIMain.py", line 625, in artscannerCallback
  File "UIMain.py", line 580, in artFilter
  File "art_saver.py", line 137, in __init__
AssertionError: Artifact attributes are not valid

之后我试了原版Amenoma的最新版（2.3.2）在扫描时没有出现同样的问题。

**Comment by zyr17** [comment]
感谢报告，请问是否方便提供出错时的圣遗物？我会之后有空的时候看下是什么问题。

**Comment by tseflcz** [comment]
![image](https://user-images.githubusercontent.com/66352689/147622763-e9016164-e26e-4671-91a4-f80bceaaceb0.png)

**Comment by zyr17** [comment]
因为太忙所以一直没来得及修。。

出现的问题是攻击力被识别成了+114然后通不过检查了。因为我这边是自己重新训练的模型所以有些结果识别不正确，出错后忘catch错误信息了。0.3.1已经修复，目前会将错误圣遗物跳过并存储图片到artifacts文件夹。

**Comment by tseflcz** [comment]
感谢大佬修复，另外，我在另一个有关优化的issue里提了一个小建议，因为不知道您有没有看到这里再说一下，我写了一个评分系统https://github.com/tseflcz/artifacts-master/， 个人觉得还挺好用的，不知道有没有可能集成到加锁工具中去。
